%%metro line: main | Main pipeline | #79706E
%%metro line: side | Assist routes | #E8A33D
%%metro font_scale: 1.9
%%metro stroke_scale: 1.6
%%metro legend: br

graph LR
    preprocess -->|main| align
    align -->|main| dedup
    dedup -->|main| multiqc
    dedup -->|side| genotype
    genotype -->|side| multiqc
    dedup -->|side| ancient
    ancient damage -->|side| multiqc
    align -->|side| metagenome
    metagenome -->|side| multiqc
    refprep -->|side| align
    align -->|side| dedup
    align -->|side| multiqc
    dedup -->|side| multiqc
