%%metro line: main | Main pipeline | #79706E
%%metro line: ref | Data acquisition | #4C78A8
%%metro line: pe | PE alignment | #54A24B
%%metro line: se | SE alignment | #F2A93B
%%metro line: report | Reporting | #F2CF5B

%%metro font_scale: 1.9
%%metro stroke_scale: 1.6
%%metro legend: br

graph LR
    get_genome["genome"] -->|ref| star_index["STAR\nindex"]
    get_annotation["annot"] -->|ref| star_index["STAR\nindex"]
    get_genome["genome"] -->|ref| bwa_index["BWA\nindex"]
    get_genome["genome"] -->|ref| genome_faidx["faidx"]
    get_annotation["annot"] -->|ref| rseqc_gtf2bed["rseqc\ngtf2bed"]
    get_sra["SRA"] -->|pe| fastp_pe["fastp\nPE"]
    fastp_pe["fastp\nPE"] -->|pe| star_align["STAR\nPE"]
    star_index["STAR\nindex"] -->|pe| star_align["STAR\nPE"]
    get_sra["SRA"] -->|se| fastp_se["fastp\nSE"]
    fastp_se["fastp\nSE"] -->|se| star_align_se["STAR\nSE"]
    get_sra["SRA"] -->|se| star_align_se_raw["STAR\nSE raw"]
    star_index["STAR\nindex"] -->|se| star_align_se["STAR\nSE"]
    star_align["STAR\nPE"] -->|main| _aligned["_aligned"]
    star_align_raw["STAR\nPE raw"] -->|main| _aligned["_aligned"]
    star_align_se["STAR\nSE"] -->|main| _aligned["_aligned"]
    star_align_se_raw["STAR\nSE raw"] -->|main| _aligned["_aligned"]
    _aligned["_aligned"] -->|main| count_matrix["counts"]
    _aligned["_aligned"] -->|main| rseqc_QC["rseqc\nQC"]
    _aligned["_aligned"] -->|main| multiqc["MultiQC"]
    count_matrix["counts"] -->|main| gene_2_symbol_counts["gene2\ncounts"]
    count_matrix["counts"] -->|main| deseq2_init["DESeq2\ninit"]
    deseq2_init["DESeq2\ninit"] -->|main| deseq2["DESeq2"]
    deseq2_init["DESeq2\ninit"] -->|main| gene_2_symbol_normcounts["gene2\nnorm"]
    deseq2_init["DESeq2\ninit"] -->|main| DESeq2_PCA["PCA"]
    deseq2["DESeq2"] -->|main| gene_2_symbol_diffexp["gene2\ndiffexp"]
    rseqc_QC["rseqc\nQC"] -->|report| multiqc["MultiQC"]
