#!/usr/bin/env python3
"""Regenerate the catalog from data/pipelines.json.

Reads the metadata of every workflow, enriches it with the Quickstart and
Fidelity sections of each staged repository's README (when the staging tree is
available locally), then emits:

  docs/javascripts/pipelines-data.js   data consumed by the catalog renderer
  docs/pipelines/<name>.md             one run-notes page per workflow

The generated files are committed, so CI only runs `mkdocs build`.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "pipelines.json"
OUT_JS = ROOT / "docs" / "javascripts" / "pipelines-data.js"
OUT_PAGES = ROOT / "docs" / "pipelines"
STAGING = pathlib.Path.home() / "Documents" / "GitHub" / "oxo-community" / "staging"

ESCAPE_TABLE = str.maketrans({"\\": "\\\\", "'": "\\'", "\n": "\\n"})


def load() -> list[dict]:
    return json.loads(DATA.read_text())


def section(text: str, heading: str) -> str:
    """Extract a `## Heading` section (until the next heading)."""
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.startswith("##") and not line.startswith("###"):
            if line[2:].strip().lstrip("#").strip().lower().startswith(heading.lower()):
                start = i
            elif start is not None:
                return "\n".join(lines[start + 1 : i]).strip()
    if start is not None:
        return "\n".join(lines[start + 1 :]).strip()
    return ""


def quickstart_command(text: str) -> str | None:
    """First `oxo-flow ` command line in the Quickstart section."""
    qs = section(text, "Quickstart")
    for line in qs.splitlines():
        line = line.strip()
        if line.startswith("oxo-flow ") and "run" in line:
            return line
    return None


def enrich(pipelines: list[dict]) -> list[dict]:
    for p in pipelines:
        readme = STAGING / p["name"] / "README.md"
        if readme.exists():
            text = readme.read_text()
            cmd = quickstart_command(text)
            if cmd:
                p["quickstart"] = cmd
            fidelity = section(text, "Fidelity")
            if fidelity:
                p["fidelity_md"] = fidelity
        p.setdefault("quickstart", f"oxo-flow run workflow/{p['name'].removeprefix('oxo-flow-')}.toml")
    return pipelines


def emit_js(pipelines: list[dict]) -> None:
    body = json.dumps(pipelines, indent=2)
    OUT_JS.write_text(
        "/* Generated by scripts/generate.py — do not edit by hand. */\n"
        f"window.OXO_PIPELINES = {body};\n"
    )


def meta_table(p: dict) -> str:
    rows = [
        ("Engine", "nf-core" if p["engine"] == "nextflow" else "snakemake"),
        ("Source", f"[{p['source']['repo']}]({p['source']['url']})"),
        ("Pinned version", f"`{p['source'].get('tag') or p['source'].get('sha', '')}`"),
        ("Ported", p.get("created", "2026-08-15")),
        ("Rules", str(p.get("rule_count", "—"))),
        ("Tools", " · ".join(p.get("tools", []))),
        ("Domain", p.get("domain", "")),
    ]
    head = "| | |\n|---:|---|\n"
    return head + "\n".join(f"| **{k}** | {v} |" for k, v in rows)


def make_page(p: dict) -> str:
    src = p["source"]
    scope = "\n".join(f"- {s}" for s in p.get("scope", []))
    excluded = "\n".join(f"- {s}" for s in p.get("excluded", [])) or "- none"
    fidelity = p.get("fidelity_md")
    parts = [
        f"# {p['title']}",
        "",
        p.get("description", ""),
        "",
        meta_table(p),
        "",
        "## Run it",
        "",
        "```bash",
        p["quickstart"],
        "```",
        "",
        "## Scope",
        "",
        "The default-parameters main path of the source pipeline was ported "
        "rule-for-rule; alternate paths are documented as excluded.",
        "",
        "**In scope**",
        "",
        scope,
        "",
        "**Excluded**",
        "",
        excluded,
    ]
    if fidelity:
        parts += ["", "## Fidelity", "", fidelity]
    parts += [
        "",
        "## Links",
        "",
        f"- Repository: [{p['name']}]({p['repo_url']})",
        f"- Upstream: [{src['repo']}]({src['url']})"
        + (f" @ `{src['tag']}`" if src.get("tag") else ""),
        f"- License: Apache-2.0 (port) · {p.get('upstream_license') or src.get('license')} (upstream)",
        "",
        "This port was created on "
        + p.get("created", "2026-08-15")
        + " and may lag behind upstream releases. See the repository's NOTICE "
        "for full attribution.",
    ]
    return "\n".join(parts) + "\n"


def main() -> int:
    pipelines = enrich(load())
    emit_js(pipelines)
    OUT_PAGES.mkdir(parents=True, exist_ok=True)
    for p in pipelines:
        (OUT_PAGES / f"{p['name']}.md").write_text(make_page(p))
    print(f"generated: {len(pipelines)} pages + pipelines-data.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
