#!/usr/bin/env python3
"""Regenerate the catalog from data/pipelines.json (registry v2).

Reads the metadata of every cataloged workflow, enriches it with the
Quickstart and Fidelity sections of each staged repository's README (when the
staging tree is available locally), then emits:

  docs/javascripts/pipelines-data.js   data consumed by the catalog renderer
  docs/pipelines/<name>.md             one run-notes page per workflow

The generated files are committed, so CI only runs `mkdocs build`.
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "pipelines.json"
OUT_JS = ROOT / "docs" / "javascripts" / "pipelines-data.js"
OUT_PAGES = ROOT / "docs" / "pipelines"
STAGING = pathlib.Path.home() / "Documents" / "GitHub" / "oxo-community" / "staging"

ENGINE_URL = (
    "https://github.com/Traitome/oxo-flow/releases/latest/download/"
    "oxo-flow-latest-x86_64-unknown-linux-gnu.tar.gz"
)


def load() -> list[dict]:
    return json.loads(DATA.read_text())


REQUIRED_FIELDS = ("name", "title", "description", "repo_url", "domain", "tags", "tools")


def validate(pipelines: list[dict]) -> None:
    """Fail loudly instead of emitting a broken/empty run-notes page."""
    names = []
    for p in pipelines:
        missing = [f for f in REQUIRED_FIELDS if not p.get(f)]
        inst = p.get("installation") or {}
        if not inst.get("engine") or not inst.get("toolchain"):
            missing.append("installation.engine/toolchain")
        if not p.get("quickstart"):
            missing.append("quickstart (or a staging README with Usage)")
        if missing:
            raise SystemExit(f"registry entry '{p.get('name', '?')}' missing: {', '.join(missing)}")
        names.append(p["name"])
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        raise SystemExit(f"duplicate registry names: {sorted(dupes)}")


def norm(heading: str) -> str:
    return heading.lower().replace(" ", "").replace("-", "").lstrip("#")


def section(text: str, heading: str) -> str:
    """Extract a `## Heading` section (until the next heading)."""
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.startswith("##") and not line.startswith("###"):
            if norm(line[2:].strip()).startswith(norm(heading)):
                start = i
            elif start is not None:
                return "\n".join(lines[start + 1 : i]).strip()
    if start is not None:
        return "\n".join(lines[start + 1 :]).strip()
    return ""


def quickstart_command(text: str) -> str | None:
    """First `oxo-flow ` command line in the Quickstart/Usage section."""
    for heading in ("Usage", "Quickstart", "Quick Start"):
        qs = section(text, heading)
        for line in qs.splitlines():
            line = line.strip()
            if line.startswith("oxo-flow ") and "run" in line:
                return line
    return None


def enrich(pipelines: list[dict]) -> list[dict]:
    for p in pipelines:
        readme = STAGING / p["name"] / "README.md"
        if readme.exists():
            text = readme.read_text()
            cmd = quickstart_command(text)
            if cmd and not p.get("quickstart"):
                p["quickstart"] = cmd
            fidelity = section(text, "Fidelity")
            if fidelity and not p.get("fidelity_md"):
                p["fidelity_md"] = fidelity
        p.setdefault("quickstart", f"oxo-flow run workflow/{p['name'].removeprefix('oxo-flow-')}.toml")
    return pipelines


def emit_js(pipelines: list[dict]) -> None:
    body = json.dumps(pipelines, indent=2)
    OUT_JS.write_text(
        "/* Generated by scripts/generate.py — do not edit by hand. */\n"
        f"window.OXO_PIPELINES = {body};\n"
    )


def badges(p: dict) -> str:
    star = ('<span class="ox-badge ox-badge--star">★ Verified</span>'
            if p.get("rating") == "verified"
            else '<span class="ox-badge">☆ Community</span>')
    origin = {
        "port": "⇄ Official port",
        "original": "✦ Original",
        "curated": "♺ Community listing",
    }.get(p.get("origin"), "♺ Community listing")
    eng = ""
    if p.get("engine") == "nextflow":
        eng = '<span class="ox-badge ox-badge--nf"><span class="dot"></span>nf-core port</span>'
    elif p.get("engine") == "snakemake":
        eng = '<span class="ox-badge ox-badge--sn"><span class="dot"></span>snakemake port</span>'
    return f'<div class="ox-page-badges">{star} <span class="ox-badge ox-badge--origin">{origin}</span> {eng}</div>'


def meta_table(p: dict) -> str:
    rows = [
        ("Rating", "★ Verified" if p.get("rating") == "verified" else "☆ Community"),
        ("Origin", p.get("origin", "curated")),
        ("Domain", p.get("domain", "")),
        ("Rules", str(p.get("rule_count", "—"))),
        ("Tools", " · ".join(p.get("tools", []))),
        ("Ported", p.get("created", "2026-08-15")),
        ("License", p.get("license", "Apache-2.0")),
    ]
    src = p.get("source")
    if src:
        rows += [
            ("Source", f"[{src['repo']}]({src['url']})"),
            ("Pinned version", f"`{src.get('tag') or src.get('sha', '')}`"),
        ]
    head = "| | |\n|---:|---|\n"
    return head + "\n".join(f"| **{k}** | {v} |" for k, v in rows)


def install_section(p: dict) -> str:
    inst = p.get("installation") or {}
    lines = [
        "## Installation",
        "",
        f"**Engine.** {inst.get('engine', 'oxo-flow >= 0.12.0')}",
        "",
        f"**Toolchain.** {inst.get('toolchain', 'containers or conda envs — pinned')}",
    ]
    if inst.get("requirements"):
        lines += ["", "**Requirements.**"] + [f"- {r}" for r in inst["requirements"]]
    lines += [
        "",
        "```bash",
        "# 1. install oxo-flow (release binary, recommended)",
        f"curl -fL -o oxo-flow.tar.gz {ENGINE_URL}",
        "tar xzf oxo-flow.tar.gz && sudo mv oxo-flow /usr/local/bin/",
        "#    or, via conda (may lag behind releases):",
        "#    conda install -c bioconda oxo-flow-cli",
        "",
        "# 2. get this workflow",
        f"git clone {p['repo_url']}",
        "```",
    ]
    return "\n".join(lines)


def make_page(p: dict) -> str:
    src = p.get("source") or {}
    scope = "\n".join(f"- {s}" for s in p.get("scope", []))
    excluded = "\n".join(f"- {s}" for s in p.get("excluded", [])) or "- none"
    fidelity = p.get("fidelity_md")
    parts = [
        f"# {p['title']}",
        "",
        badges(p),
        "",
        p.get("description", ""),
        "",
        meta_table(p),
        "",
        "## Run it",
        "",
        "```bash",
        p["quickstart"],
        "```",
        "",
        install_section(p),
    ]
    if src:
        parts += [
            "",
            "## Scope",
            "",
            "The default-parameters main path of the source pipeline was ported "
            "rule-for-rule; alternate paths are documented as excluded.",
            "",
            "**In scope**",
            "",
            scope,
            "",
            "**Excluded**",
            "",
            excluded,
        ]
    if fidelity:
        parts += ["", "## Fidelity", "", fidelity]
    parts += [
        "",
        "## Links",
        "",
        f"- Repository: [{p['name']}]({p['repo_url']})",
    ]
    if src:
        parts += [
            f"- Upstream: [{src['repo']}]({src['url']})"
            + (f" @ `{src['tag']}`" if src.get("tag") else ""),
            f"- License: {p.get('license', 'Apache-2.0')} (this workflow)"
            + (f" · {p.get('upstream_license') or src.get('license')} (upstream)" if src else ""),
            "",
            "Created on " + p.get("created", "2026-08-15")
            + " — this port may lag behind upstream releases. See the "
            "repository's NOTICE for full attribution.",
        ]
    return "\n".join(parts) + "\n"


def main() -> int:
    pipelines = enrich(load())
    validate(pipelines)
    emit_js(pipelines)
    OUT_PAGES.mkdir(parents=True, exist_ok=True)
    for p in pipelines:
        (OUT_PAGES / f"{p['name']}.md").write_text(make_page(p))
    print(f"generated: {len(pipelines)} pages + pipelines-data.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
